"""change of data

Revision ID: 827ab9a9dde1
Revises: a316472cd7b6
Create Date: 2024-05-04 03:16:58.415650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827ab9a9dde1'
down_revision: Union[str, None] = 'a316472cd7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('Nitrogen', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('Phosphorus', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('Potassium', sa.Float(), nullable=True))
    op.drop_column('sensor_data', 'device_id')
    op.drop_column('sensor_data', 'lat')
    op.drop_column('sensor_data', 'battery')
    op.drop_column('sensor_data', 'lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_data', sa.Column('battery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_data', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_data', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sensor_data', 'Potassium')
    op.drop_column('sensor_data', 'Phosphorus')
    op.drop_column('sensor_data', 'Nitrogen')
    # ### end Alembic commands ###
